import "fonts/GeosansLight.ttf";

import { Theme } from "base/theme.slint";
import { AppLogic } from "logic/desktop-window-logic.slint";
import { Button } from "base/button.slint";

export { AppLogic }

export component App inherits Window {
    in-out property <string> file_path;

    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-weight: Theme.normal-font-weight;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;

    VerticalLayout {

        Text {
            text: file_path;
            visible: !file_path.is-empty;
        }

        Button {
            text: "select file";
            bg-pressed-color: Colors.transparent;
            clicked => {
                AppLogic.file_pick()
            }
        }
    }
}
